[Component]
    Components = [
        { Name = "GLOBAL.SF Tech.Online Store Company.Store Services.Ad Service.adservice", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
     ]    
    Version = "1.2.2"
    ChartName = "chart/adservice"
    DockerRepo = "quay.io/hipsterstore/adservice"
    GitUrl = "https://github.com/ortelius/store-adservice"
    CustomAction = "GLOBAL.HelmChart"