steps:
# Build the image and save details as part of the LABEL
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - 'DOCKER_CONFIG=/workspace/docker-config'
  args: ["-c", "export GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD);env"]
  
