steps:
# Build the image and save details as part of the LABEL
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - 'DOCKER_CONFIG=/workspace/docker-config'
  args: ["-c", "ls -lRa"]
  
